export default [
  {
    name: "name",
    type: "text",
    variant: "regular",
    placeholder: "Please enter your name here...",
  },
  {
    name: "email",
    type: "email",
    variant: "regular",
    placeholder: "Please enter your email here...",
  },
  {
    name: "password",
    type: "password",
    variant: "regular",
    placeholder: "Please enter your password here...",
  },
  {
    name: "repassword",
    type: "password",
    variant: "regular",
    placeholder: "Please enter your password again...",
  },
  {
    name: "phone",
    type: "string",
    variant: "regular",
    placeholder: "Please enter your phone number here...",
  },
  {
    name: "location",
    type: "text",
    variant: "location",
    placeholder: "Please enter your location here...",
    data: [
      "Dhaka",
      "Chittagong",
      "Rajshahi",
      "Barisal",
      "Khulna",
      "Rangpur",
      "Shylet",
      "Cumilla",
    ],
  },
  {
    name: "date",
    type: "date",
    variant: "regular",
    placeholder: "Please enter your Birthday date here...",
  },
  {
    name: "color",
    type: "color",
    variant: "regular",
    placeholder: "Please enter your favourite color here...",
  },
  {
    name: "age",
    type: "string",
    variant: "regular",
    placeholder: "Please enter your age here...",
  },
  {
    name: "fromtime",
    type: "time",
    variant: "time",
    placeholder: "Please enter sleeping start time here...",
  },
  {
    name: "totime",
    type: "time",
    variant: "time",
    placeholder: "Please enter sleeping end time here...",
  },
  {
    name: "married",
    type: "checkbox",
    variant: "married",
    placeholder: "Please select your married status here...",
  },
  {
    name: "gender",
    type: "radio",
    variant: "gender",
    placeholder: "Please select your gender here...",
    data: [
      { type: "radio", title: "Male" },
      { type: "radio", title: "Female" },
    ],
  },
];
